### ISSUE TITLE
Search for "grounded theory" returns unexpected questions

### ISSUE THREAD

**Issue by alopezlago** [grapesmoker/qbdb3.0#1]
1. Search for (including quotes)

"grounded theory"

Expected:
    George Oppen bonus on grounded theory
Actual:
    Two questions, which appear to match the string 'theory"'.

**Comment by grapesmoker** [comment]
Hmm, weird. I would have to figure out how exactly Xapian does its searching.

**Comment by grapesmoker** [comment]
no longer relevant because we use elastic now
