### ISSUE TITLE
Pressing Enter on search box leads to blank page

### ISSUE THREAD

**Issue by alopezlago** [grapesmoker/qbdb3.0#2]
1. Type in some text into the search box in the Search page
2. Hit enter while the search box has focus

**Expected:**
    Search results are displayed.
**Actual:**
    Middle of the page is blank.

The URL generated by hitting enter is:
http://qbdb.grapesmoker.net/?q=searchTerm&models=tossup&models=bonus&fields=question&fields=answer#search

**Comment by grapesmoker** [comment]
Yeah, I fucked that up. I have a fix for this that will be committed in the next few days.

**Comment by grapesmoker** [comment]
so old
